[package]
name = "pf_age_ndk"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ndk-sys="0.3.0"
ndk ="0.6.0"